
# GROQ_API_KEY: "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"
# GROQ_API_KEY: "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"
GROQ_API_KEY: "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"
# GROQ_API_KEY: "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"

SERPER_API_KEY: "48d3d24f22dd9ec8166f0087bbdfac17df09dc77"
